before:
  hooks:
    # You may remove this if you don't use go modules.
    #- go mod download
    # you may remove this if you don't need go generate
    #- go generate ./...
    #- make validate
#
#
#  BUILDS
#
#
builds:
  - id: linux-newrelic-infra
    main: ./cmd/newrelic-infra
    binary: newrelic-infra
    env:
    - CGO_ENABLED=0
    goos:
    - linux
    ldflags:
    - -s -w -X main.integrationVersion={{.Version}}
    goarch:
    - amd64
#    - arm
#    - arm64
    - 386
#    - mips
#    - mips64
#    - mipsle
#    - mips64le
#    - ppc64le
#    - s390x
  - id: linux-newrelic-infra-ctl
    main: ./cmd/newrelic-infra-ctl
    binary: newrelic-infra-ctl
    env:
    - CGO_ENABLED=0
    goos:
    - linux
    ldflags:
    - -s -w -X main.integrationVersion={{.Version}}
    goarch:
    - amd64
    - 386

  - id: linux-newrelic-infra-service
    main: ./cmd/newrelic-infra-service
    binary: newrelic-infra-service
    env:
    - CGO_ENABLED=0
    goos:
    - linux
    ldflags:
    - -s -w -X main.version={{.Version}}
    - -s -w -X main.commit={{.Commit}}
    goarch:
    - amd64
    - 386

nfpms:
  - id: centos-8-infrastructure-agent
    builds:
      - linux-newrelic-infra
      - linux-newrelic-infra-ctl
      - linux-newrelic-infra-service
    package_name: newrelic-infra
    file_name_template: "newrelic-infra-{{ .Env.TAG }}.el8.{{ .Arch }}"
    vendor: 'New Relic, Inc.'
    homepage: 'https://docs.newrelic.com/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-197'
    maintainer: 'caos-team@newrelic.com'
    description: 'New Relic Infrastructure provides flexible, dynamic server monitoring. With real-time data collection and a UI that scales from a handful of hosts to thousands, Infrastructure is designed for modern Operations teams with fast-changing systems.'
    license: 'Copyright (c) 2008-2020 New Relic, Inc. All rights reserved.'
    formats:
      - rpm
    bindir: /usr/bin
    files:
      '/other-repos/nri-docker/etc/newrelic-infra/integrations.d/docker-config.yml': '/etc/newrelic-infra/integrations.d/docker-config.yml'
      'external_content/examples/logging/linux/file.yml.example': '/etc/newrelic-infra/logging.d/file.yml.example'
      'external_content/examples/logging/linux/fluentbit.yml.example': '/etc/newrelic-infra/logging.d/fluentbit.yml.example'
      'external_content/examples/logging/linux/syslog.yml.example': '/etc/newrelic-infra/logging.d/syslog.yml.example'
      'external_content/examples/logging/linux/systemd.yml.example': '/etc/newrelic-infra/logging.d/systemd.yml.example'
      'external_content/examples/logging/linux/tcp.yml.example': '/etc/newrelic-infra/logging.d/tcp.yml.example'
      'build/package/systemd/newrelic-infra.service': '/etc/systemd/system/newrelic-infra.service'
      'LICENSE': '/var/db/newrelic-infra/LICENSE.txt'
      '/other-repos/nri-docker/var/db/newrelic-infra/newrelic-integrations/bin/nri-docker': '/var/db/newrelic-infra/newrelic-integrations/bin/nri-docker'
      '/other-repos/nri-flex/nri-flex': '/var/db/newrelic-infra/newrelic-integrations/bin/nri-flex'
      '/other-repos/fluent-bit/nrfb/fluent-bit': '/var/db/newrelic-infra/newrelic-integrations/logging/fluent-bit'
      '/other-repos/fluent-bit/nrfb/out_newrelic.so': '/var/db/newrelic-infra/newrelic-integrations/logging/out_newrelic.so'
      '/other-repos/fluent-bit/nrfb/parsers.conf':  '/var/db/newrelic-infra/newrelic-integrations/logging/parsers.conf'
    empty_folders:
      - /var/db/newrelic-infra/custom-integrations
      - /var/db/newrelic-infra/integrations.d
      - /var/log/newrelic-infra
      - /var/run/newrelic-infra
    epoch: 0
    release: 1.el8
    replacements:
      amd64: x86_64

release:
  prerelease: true

checksum:
  disable: true

signs:
  - artifacts: all
    cmd: bash
    args:
    - '-c'
    - ./cicd/scripts/rpm_sign.sh "${signature}" "${artifact}"