before:
  hooks:
    # You may remove this if you don't use go modules.
    #- go mod download
    # you may remove this if you don't need go generate
    #- go generate ./...
    #- make validate

builds:
  - main: ./cmd/newrelic-infra
    env:
    - CGO_ENABLED=0
    goos:
    - linux
    ldflags:
    - -s -w -X main.integrationVersion={{.Version}}
    goarch:
    - amd64
#    - arm
#    - arm64
#    - 386
#    - mips
#    - mips64
#    - mipsle
#    - mips64le
#    - ppc64le
#    - s390x

archives:
  - replacements:
      linux: Linux
      x86_64: amd64
    name_template: "{{ .Env.PROJECTNAME }}_{{ .Env.TAG }}_{{ .Arch }}"
    format: tar.gz
    files:
    - licence*
    - LICENCE*
    - license*
    - LICENSE*
    - readme*
    - README*
    - changelog*
    - CHANGELOG*

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  filters:
    exclude:
    - '^docs:'
    - '^test:'

nfpms:
  - file_name_template: "{{ .Env.PROJECTNAME }}_{{ .Env.TAG }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

    vendor: "New Relic, Inc."
    homepage: "https://www.newrelic.com/infrastructure"
    maintainer: "New Relic Infrastructure Team <infrastructure-eng@newrelic.com>"
    description: "New Relic Infrastructure kafka Integration extend the core New Relic\nInfrastructure agent's capabilities to allow you to collect metric and\nlive state data from kafka components."
    license: "https://newrelic.com/terms (also see LICENSE.txt installed with this package)"

    # Formats to be generated.
    formats:
      - deb
      - rpm

    # Override default /usr/local/bin destination for binaries
    bindir: "../var/db/newrelic-infra/newrelic-integrations/bin"

    files:
      "./*-config.yml.sample": "../etc/newrelic-infra/integrations.d"
      "CHANGELOG.md": "../usr/share/doc/nri-kafka"
      "README.md":  "../usr/share/doc/nri-kafka"
      "LICENSE": "../usr/share/doc/nri-kafka"

    config_files:
      "kafka-definition.yml": "../var/db/newrelic-infra/newrelic-integrations/kafka-definition.yml"

    dependencies:
      - "newrelic-infra"
      - "nrjmx"

    overrides:
      rpm:
        replacements:
          amd64: x86_64 # Exceptions in the name, .deb are amd64, .rpm are x86_64

release:
  prerelease: true

signs:
  - artifacts: checksum
    cmd: gpg2
    args: ["--batch", "-u", "{{ .Env.GPG_MAIL }}", "--passphrase", "{{ .Env.GPG_PASSPHRASE }}", "--pinentry-mode", "loopback", "--output", "${signature}", "--detach-sign", "${artifact}"]

