version: '3'

services:

  tarballcreator:
    build:
      context: dockerfiles/tarball-creator/
      dockerfile: Dockerfile
    volumes:
      - ${GITHUB_WORKSPACE}:/${REPO_FULL_NAME}/
    working_dir: /${REPO_FULL_NAME}
    environment:
      - GITHUB_TOKEN=$GITHUB_TOKEN
      - TAG=$TAG
#      - TAG=v1.0.27
      - REPO_FULL_NAME=$REPO_FULL_NAME




