version: '3'

services:

  release:
    build:
      context: dockerfiles/docker-image-creator/
      dockerfile: Dockerfile
    volumes:
      - ${GITHUB_WORKSPACE}:/${REPO_FULL_NAME}/
      - /var/run/docker.sock:/var/run/docker.sock:rw
    working_dir: /${REPO_FULL_NAME}
    environment:
      - GITHUB_TOKEN=$GITHUB_TOKEN
      - PIPELINE_ACTION=$PIPELINE_ACTION
      - TAG=$TAG
      - REPO_FULL_NAME=$REPO_FULL_NAME
      - DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME
      - DOCKERHUB_PASSWORD=$DOCKERHUB_PASSWORD
      - DOCKERHUB_NAMESPACE=$DOCKERHUB_NAMESPACE