version: '3'

services:

  release:
    build:
      context: dockerfiles/harvest-binary-creator/
      dockerfile: Dockerfile
    volumes:
      - ${GITHUB_WORKSPACE}:/code/
    working_dir: /code


