version: '3'

services:

  goreleaser:
    build:
      context: dockerfiles/goreleaser/
      dockerfile: Dockerfile
    volumes:
      - ${GITHUB_WORKSPACE}:/go/src/github.com/${REPO_FULL_NAME}/
    working_dir: /go/src/github.com/${REPO_FULL_NAME}
    environment:
      - AWS_S3_FQDN=$AWS_S3_FQDN
      - GITHUB_TOKEN=$GITHUB_TOKEN
      - GITHUB_REF=$GITHUB_REF
      - GITHUB_PUSH_PRERELEASE_ASSETS=$GITHUB_PUSH_PRERELEASE_ASSETS
      - TAG=$TAG
      - REPO_FULL_NAME=$REPO_FULL_NAME
      - PROJECTNAME=$PROJECTNAME
      - GOPATH=$GOPATH
      - GPG_APT_PRIVATE_KEY=$GPG_APT_PRIVATE_KEY
      - GPG_APT_PASSPHRASE=$GPG_APT_PASSPHRASE
      - GPG_APT_MAIL=$GPG_APT_MAIL
      - NRI_DOCKER_VERSION=$NRI_DOCKER_VERSION
      - NRI_DOCKER_ARCH=$NRI_DOCKER_ARCH
      - NRI_FLEX_VERSION=$NRI_FLEX_VERSION
      - NRI_FLEX_OS=$NRI_FLEX_OS
      - NRI_FLEX_ARCH=$NRI_FLEX_ARCH
      - FLUENTBIT_VERSION=$FLUENTBIT_VERSION




