name: Pipeline

on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    types:
      - closed
  release:
    types:
      - prereleased
      - released
    tags:
      - 'v*'

env:
  TAG: ${{ github.event.release.tag_name }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  REPO_NAME: ${{ github.event.repository.name }}
  REPO_FULL_NAME: ${{ github.event.repository.full_name }}
  GPG_APT_PRIVATE_KEY: ${{ secrets.GPG_APT_PRIVATE_KEY_BASE64 }} # base64 encoded
  GPG_APT_PASSPHRASE: ${{ secrets.GPG_APT_PASSPHRASE }}
  GPG_APT_MAIL: 'infrastructure-eng@newrelic.com' # Mail associated to GPG key
  GPG_RPM_PRIVATE_KEY: ${{ secrets.GPG_RPM_PRIVATE_KEY_BASE64 }} # base64 encoded
  GPG_RPM_PASSPHRASE: ${{ secrets.GPG_RPM_PASSPHRASE }}
  GPG_RPM_MAIL: 'infrastructure-eng@newrelic.com'

jobs:
#
#
#  Build binaries/packages
#
#
  build-linux-binaries-and-push-github:
    name: build Linux binaries/packages
    if: github.event.action == 'released'
    runs-on: ubuntu-latest
    env:
      GITHUB_PUSH_RELEASE_ASSETS: false
    steps:
      - uses: actions/checkout@v2
      - name: Unshallowify the repo clone # So GoReleaser can generate the changelog properly
        run: git fetch --prune --unshallow
      - name: Check GH event is Release or Prerelease
        if: github.event_name == 'release'
        run: echo "::set-env name=GITHUB_PUSH_RELEASE_ASSETS::true"
      - name: Create binaries & Push to GH Release Assets if Release/Prerelease
        env:
          GITHUB_REF: $GITHUB_REF
          PROJECTNAME: $REPO_NAME
          GOPATH: '/go'
        run: |
          docker-compose --file docker_compose_goreleaser.yml run release
      - name: Upload Linux artifacts to GH Workflow Artifacts Cache
        if: github.event.pull_request.merged
        uses: actions/upload-artifact@v2
        with:
          name: Linux-artifacts
          path: dist/**/*

